### ISSUE TITLE
Document deploy failure hook

### ISSUE THREAD

**Issue by seenmyfate** [capistrano/documentation#39]
Document feature added [by this PR](https://github.com/capistrano/capistrano/pull/756)

**Comment by damienalexandre** [comment]
:+1: very useful feature.

Also this page: http://capistranorb.com/documentation/getting-started/rollbacks/
could explain why and how rollbacks works (the fact that they are not automatic in case of failure for example).

**Comment by leehambley** [comment]
@damienalexandre the docs are a great place to start contributing if you've just been through the pain of figuring out how this worked without any useful docs.

If you haven't figured it out yet:

* we don't roll back by default because it's possibly destructive (plugins, deleted builds, no way to see how it worked out, etc, possibly risky trying to guess (on our side) what the previous build was, etd)
* the rollback flow is documented in http://capistranorb.com/documentation/getting-started/flow/

**Comment by will-in-wi** [comment]
Duplicated by and fixed in https://github.com/capistrano/documentation/issues/124

**Comment by will-in-wi** [comment]
I stand corrected, the deploy:failure hook does not appear to be documented. Rollback is documented.

**Comment by will-in-wi** [comment]
Added some possible docs in https://github.com/capistrano/documentation/pull/157.
